// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using UnitTestProject1;
[TestFixture]
public class LoginTest: TestBase
{
    private AccountData account = new AccountData("nasasas930@fpxnet.com", "EYWRnnVqgNEdgN3Cdr62Lolqle7VOryQ");
    private TodoData todo = new TodoData("TITLE ", "DESCRIPTION");
    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
        ResizeWindowToDesktopMode();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    public void login()
    {
        Login(account);
    }

    [Test]
    public void createToDo()
    {
        Login(account);
        AddTodo(todo);
        Wait(5);
    }
}
